CREATE TABLE [dbo].[tbl_Static_Items](
	[itemId] [bigint] NOT NULL,
	[name] [varchar](200) NOT NULL,
 CONSTRAINT [PK_tbl_Static_Items] PRIMARY KEY CLUSTERED 
(
	[itemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


