namespace BDL.Objects
{
    public class ParticipantStats
    {
        public long assists;
        public long champLevel;
        //public long combatPlayerScore;
        public long deaths;
        public long doubleKills;
        public bool firstBloodAssist;
        public bool firstBloodKill;
        public bool firstInhibitorAssist;
        public bool firstInhibitorKill;
        public bool firstTowerAssist;
        public bool firstTowerKill;
        public long goldEarned;
        public long goldSpent;
        public long inhibitorKills;
        public long item0;
        public long item1;
        public long item2;
        public long item3;
        public long item4;
        public long item5;
        public long item6;
        public long killingSprees;
        public long kills;
        public long largestCriticalStrike;
        public long largestKillingSpree;
        public long largestMultikill;
        public long magicDamageDealt;
        public long magicDamageDealtToChampions;
        public long magicDamageTaken;
        public long minionsKilled;
        public long neutralMinionsKilled;
        public long neutralMinionsKilledEnemyJungle;
        public long neutralMinionsKilledTeamJungle;
        //public long nodeCapture;
        //public long nodeCaptureAssist;
        //public long nodeNeutralize;
        //public long nodeNeutralizeAssist;
        //public long objectivePlayerScore;
        public long pentaKills;
        public long physicalDamageDealt;
        public long physicalDamageDealtToChampions;
        public long physicalDamageTaken;
        public long quadraKills;
        public long sightWardsBoughtInGame;
        //public long teamObjective;
        public long totalDamageDealt;
        public long totalDamageDealtToChampions;
        public long totalDamageTaken;
        public long totalHeal;
        //public long totalPlayerScore;
        //public long totalScoreRank;
        public long totalTimeCrowdControlDealt;
        public long totalUnitsHealed;
        public long towerKills;
        public long tripleKills;
        public long trueDamageDealt;
        public long trueDamageDealtToChampions;
        public long trueDamageTaken;
        public long unrealKills;
        public long visionWardsBoughtInGame;
        public long wardsKilled;
        public long wardsPlaced;
        public bool winner;
    }
}
