//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BDL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;champion&quot;,
        ///  &quot;version&quot;: &quot;5.15.1&quot;,
        ///  &quot;data&quot;: {
        ///    &quot;35&quot;: {
        ///      &quot;id&quot;: 35,
        ///      &quot;key&quot;: &quot;Shaco&quot;,
        ///      &quot;name&quot;: &quot;Shaco&quot;,
        ///      &quot;title&quot;: &quot;the Demon Jester&quot;
        ///    },
        ///    &quot;36&quot;: {
        ///      &quot;id&quot;: 36,
        ///      &quot;key&quot;: &quot;DrMundo&quot;,
        ///      &quot;name&quot;: &quot;Dr. Mundo&quot;,
        ///      &quot;title&quot;: &quot;the Madman of Zaun&quot;
        ///    },
        ///    &quot;33&quot;: {
        ///      &quot;id&quot;: 33,
        ///      &quot;key&quot;: &quot;Rammus&quot;,
        ///      &quot;name&quot;: &quot;Rammus&quot;,
        ///      &quot;title&quot;: &quot;the Armordillo&quot;
        ///    },
        ///    &quot;34&quot;: {
        ///      &quot;id&quot;: 34,
        ///      &quot;key&quot;: &quot;Anivia&quot;,
        ///      &quot;name&quot;: &quot;Anivia&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChampData {
            get {
                return ResourceManager.GetString("ChampData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;item&quot;,
        ///  &quot;version&quot;: &quot;5.15.1&quot;,
        ///  &quot;basic&quot;: {
        ///    &quot;id&quot;: 0,
        ///    &quot;name&quot;: &quot;&quot;,
        ///    &quot;group&quot;: &quot;&quot;,
        ///    &quot;description&quot;: &quot;&quot;,
        ///    &quot;sanitizedDescription&quot;: &quot;&quot;,
        ///    &quot;colloq&quot;: &quot;&quot;,
        ///    &quot;plaintext&quot;: &quot;&quot;,
        ///    &quot;consumed&quot;: false,
        ///    &quot;stacks&quot;: 1,
        ///    &quot;depth&quot;: 1,
        ///    &quot;consumeOnFull&quot;: false,
        ///    &quot;from&quot;: [
        ///      
        ///    ],
        ///    &quot;into&quot;: [
        ///      
        ///    ],
        ///    &quot;specialRecipe&quot;: 0,
        ///    &quot;inStore&quot;: true,
        ///    &quot;hideFromAll&quot;: false,
        ///    &quot;requiredChampion&quot;: &quot;&quot;,
        ///    &quot;tags&quot;: [
        ///      
        ///    ],
        ///    &quot;maps&quot;: {
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemData {
            get {
                return ResourceManager.GetString("ItemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;summoner&quot;,
        ///  &quot;version&quot;: &quot;5.15.1&quot;,
        ///  &quot;data&quot;: {
        ///    &quot;3&quot;: {
        ///      &quot;name&quot;: &quot;Exhaust&quot;,
        ///      &quot;description&quot;: &quot;Exhausts target enemy champion, reducing their Movement Speed and Attack Speed by 30%, their Armor and Magic Resist by 10, and their damage dealt by 40% for 2.5 seconds.&quot;,
        ///      &quot;summonerLevel&quot;: 4,
        ///      &quot;id&quot;: 3,
        ///      &quot;key&quot;: &quot;SummonerExhaust&quot;
        ///    },
        ///    &quot;21&quot;: {
        ///      &quot;name&quot;: &quot;Barrier&quot;,
        ///      &quot;description&quot;: &quot;Shields your champion for 115-455 (depending on champion level) for 2 se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SumSpellData {
            get {
                return ResourceManager.GetString("SumSpellData", resourceCulture);
            }
        }
    }
}
