//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIGrabber.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APIGrabber.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///577644641, 
        ///577648271, 
        ///577648304, 
        ///577648523, 
        ///577649221, 
        ///577649242, 
        ///577649322, 
        ///577649400, 
        ///577649685, 
        ///577649760, 
        ///577649769, 
        ///577649840, 
        ///577649953, 
        ///577654169, 
        ///577654985, 
        ///577656153, 
        ///577656279, 
        ///577656396, 
        ///577656450, 
        ///577656499, 
        ///577656573, 
        ///577656577, 
        ///577656777, 
        ///577656875, 
        ///577657043, 
        ///577657139, 
        ///577657259, 
        ///577657285, 
        ///577657415, 
        ///577657513, 
        ///577657589, 
        ///577657886, 
        ///577657889, 
        ///577657970, 
        ///577657994, 
        ///577658057, 
        ///577658180, 
        ///577658335, 
        ///577658444, 
        ///57 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BR {
            get {
                return ResourceManager.GetString("BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///1216093817, 
        ///1216094841, 
        ///1216095091, 
        ///1216095160, 
        ///1216095448, 
        ///1216095637, 
        ///1216095705, 
        ///1216095778, 
        ///1216096180, 
        ///1216096235, 
        ///1216104497, 
        ///1216106029, 
        ///1216151578, 
        ///1216151952, 
        ///1216151994, 
        ///1216152191, 
        ///1216152360, 
        ///1216152524, 
        ///1216152533, 
        ///1216152610, 
        ///1216152623, 
        ///1216153126, 
        ///1216153191, 
        ///1216153417, 
        ///1216153523, 
        ///1216153574, 
        ///1216153705, 
        ///1216177135, 
        ///1216177286, 
        ///1216177476, 
        ///1216177538, 
        ///1216177540, 
        ///1216177690, 
        ///1216177723, 
        ///1216177766, 
        ///1216177807, 
        ///12161 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EUNE {
            get {
                return ResourceManager.GetString("EUNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///2231715499, 
        ///2231737049, 
        ///2231737101, 
        ///2231737950, 
        ///2231738122, 
        ///2231739295, 
        ///2231739365, 
        ///2231739455, 
        ///2231739522, 
        ///2231739566, 
        ///2231739657, 
        ///2231739770, 
        ///2231739872, 
        ///2231739944, 
        ///2231740064, 
        ///2231740088, 
        ///2231740093, 
        ///2231740138, 
        ///2231740151, 
        ///2231743276, 
        ///2231744111, 
        ///2231744194, 
        ///2231744515, 
        ///2231744567, 
        ///2231744797, 
        ///2231744888, 
        ///2231745058, 
        ///2231745090, 
        ///2231745448, 
        ///2231745729, 
        ///2231746041, 
        ///2231746132, 
        ///2231746147, 
        ///2231746268, 
        ///2231746521, 
        ///2231746913, 
        ///22317 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EUW {
            get {
                return ResourceManager.GetString("EUW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///2004629307, 
        ///2004629949, 
        ///2004634632, 
        ///2004634896, 
        ///2004635204, 
        ///2004635353, 
        ///2004635796, 
        ///2004635812, 
        ///2004636379, 
        ///2004641785, 
        ///2004641930, 
        ///2004642796, 
        ///2004642895, 
        ///2004651691, 
        ///2004660217, 
        ///2004660316, 
        ///2004629611, 
        ///2004634766, 
        ///2004635436, 
        ///2004635973, 
        ///2004642319, 
        ///2004643015, 
        ///2004650714, 
        ///2004651500, 
        ///2004660315, 
        ///2004635105, 
        ///2004636339, 
        ///2004642269, 
        ///2004642280, 
        ///2004642523, 
        ///2004642873, 
        ///2004643017, 
        ///2004651543, 
        ///2004651840, 
        ///2004652728, 
        ///2004652764, 
        ///20046 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KR {
            get {
                return ResourceManager.GetString("KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///190209588, 
        ///190224615, 
        ///190224854, 
        ///190225039, 
        ///190225148, 
        ///190225310, 
        ///190225469, 
        ///190225517, 
        ///190225545, 
        ///190225590, 
        ///190225626, 
        ///190225708, 
        ///190225765, 
        ///190225896, 
        ///190225915, 
        ///190225981, 
        ///190226053, 
        ///190226206, 
        ///190226209, 
        ///190226225, 
        ///190226293, 
        ///190226341, 
        ///190226520, 
        ///190226548, 
        ///190226619, 
        ///190226664, 
        ///190226716, 
        ///190226773, 
        ///190226803, 
        ///190226881, 
        ///190226961, 
        ///190227099, 
        ///190227231, 
        ///190227360, 
        ///190227512, 
        ///190227716, 
        ///190227719, 
        ///190227756, 
        ///190227801, 
        ///19 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LAN {
            get {
                return ResourceManager.GetString("LAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///232488163, 
        ///232488978, 
        ///232489149, 
        ///232489927, 
        ///232493919, 
        ///232494504, 
        ///232494784, 
        ///232494905, 
        ///232495065, 
        ///232495139, 
        ///232495151, 
        ///232495241, 
        ///232495400, 
        ///232495458, 
        ///232495761, 
        ///232495877, 
        ///232495888, 
        ///232495896, 
        ///232495982, 
        ///232495996, 
        ///232496275, 
        ///232496497, 
        ///232496588, 
        ///232496864, 
        ///232497081, 
        ///232497108, 
        ///232497217, 
        ///232497345, 
        ///232497379, 
        ///232497381, 
        ///232502370, 
        ///232502910, 
        ///232502960, 
        ///232503117, 
        ///232503265, 
        ///232503412, 
        ///232503612, 
        ///232503688, 
        ///232503750, 
        ///23 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LAS {
            get {
                return ResourceManager.GetString("LAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///1907069332, 
        ///1907069429, 
        ///1907069695, 
        ///1907126170, 
        ///1907126706, 
        ///1907126928, 
        ///1907127301, 
        ///1907127911, 
        ///1907127945, 
        ///1907128270, 
        ///1907128585, 
        ///1907128742, 
        ///1907128824, 
        ///1907129079, 
        ///1907129141, 
        ///1907129610, 
        ///1907129669, 
        ///1907152106, 
        ///1907156776, 
        ///1907157315, 
        ///1907157392, 
        ///1907157666, 
        ///1907157876, 
        ///1907157885, 
        ///1907157964, 
        ///1907158047, 
        ///1907158238, 
        ///1907158330, 
        ///1907158657, 
        ///1907159000, 
        ///1907159096, 
        ///1907159117, 
        ///1907159224, 
        ///1907159424, 
        ///1907159514, 
        ///1907180370, 
        ///19071 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///99204913, 
        ///99204927, 
        ///99205051, 
        ///99210083, 
        ///99210193, 
        ///99210075, 
        ///99210146, 
        ///99204983, 
        ///99205109, 
        ///99205170, 
        ///99210160, 
        ///99210205, 
        ///99210222, 
        ///99210237, 
        ///99210248, 
        ///99205064, 
        ///99210242, 
        ///99210270, 
        ///99205102, 
        ///99205273, 
        ///99210243, 
        ///99210276, 
        ///99210343, 
        ///99205181, 
        ///99205201, 
        ///99205219, 
        ///99210218, 
        ///99210312, 
        ///99210397, 
        ///99210447, 
        ///99210465, 
        ///99205266, 
        ///99210401, 
        ///99210489, 
        ///99205159, 
        ///99205267, 
        ///99205281, 
        ///99205322, 
        ///99205326, 
        ///99210439, 
        ///99210444, 
        ///99205390, 
        ///99205 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OCE {
            get {
                return ResourceManager.GetString("OCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///74115014, 
        ///74115134, 
        ///74115204, 
        ///74115221, 
        ///74122168, 
        ///74122196, 
        ///74109198, 
        ///74115203, 
        ///74115321, 
        ///74121962, 
        ///74115323, 
        ///74115338, 
        ///74122071, 
        ///74122153, 
        ///74122281, 
        ///74109331, 
        ///74109374, 
        ///74122237, 
        ///74109332, 
        ///74109380, 
        ///74115289, 
        ///74115310, 
        ///74122234, 
        ///74122261, 
        ///74109421, 
        ///74115343, 
        ///74115426, 
        ///74122223, 
        ///74109412, 
        ///74115364, 
        ///74115431, 
        ///74115498, 
        ///74122282, 
        ///74122294, 
        ///74109443, 
        ///74115449, 
        ///74109429, 
        ///74109441, 
        ///74122387, 
        ///74122404, 
        ///74109420, 
        ///74109464, 
        ///74122 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RU {
            get {
                return ResourceManager.GetString("RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///286749962, 
        ///286749991, 
        ///286753219, 
        ///286753494, 
        ///286753670, 
        ///286754175, 
        ///286760298, 
        ///286760678, 
        ///286760738, 
        ///286748610, 
        ///286753307, 
        ///286753367, 
        ///286753521, 
        ///286753523, 
        ///286753685, 
        ///286753833, 
        ///286753955, 
        ///286753981, 
        ///286754033, 
        ///286754461, 
        ///286760902, 
        ///286760933, 
        ///286761328, 
        ///286761440, 
        ///286753347, 
        ///286753476, 
        ///286753678, 
        ///286753777, 
        ///286753798, 
        ///286754209, 
        ///286754227, 
        ///286754248, 
        ///286754405, 
        ///286754444, 
        ///286754556, 
        ///286754712, 
        ///286760468, 
        ///286761452, 
        ///286761602, 
        ///28 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
    }
}
